# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-22 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='adderss',
            new_name='address',
        ),
    ]
